from ...models.service import EancomErreur as EancomErreur, EancomInterchange as EancomInterchange, EancomNAD as EancomNAD, EancomServiceMessage as EancomServiceMessage
from ...utils.exceptions import SegmentInconnuWarning as SegmentInconnuWarning
from _typeshed import Incomplete
from dataclasses import dataclass, field

def parse_eancom(content: str) -> EancomInterchange: ...

@dataclass
class _MessageContext:
    identification_document: str = ...
    type_acquittement: str = ...
    date_creation: str = ...
    format_date_creation: str = ...
    reference_acquittee: str = ...
    date_traitement: str | None = ...
    format_date_traitement: str | None = ...
    date_lecture: str | None = ...
    format_date_lecture: str | None = ...
    parties: list[EancomNAD] = field(default_factory=Incomplete)
    erreur: EancomErreur | None = ...
    nombre_segments: str | None = ...
