from ..models.connector import RemoteFile as RemoteFile
from .config import DilicomConfig as DilicomConfig, load_dilicom_config as load_dilicom_config
from .decorators import retry_sftp as retry_sftp
from .exceptions import DilicomAuthenticationError as DilicomAuthenticationError, DilicomConnectionError as DilicomConnectionError, DilicomSFTPError as DilicomSFTPError
from _typeshed import Incomplete
from pathlib import Path
from types import TracebackType

logger: Incomplete

class Connector:
    config: DilicomConfig
    timeout: Incomplete
    client: Incomplete
    transport: Incomplete
    sftp: Incomplete
    def __init__(self, *, timeout: int = 30, env_path: str | None = None) -> None: ...
    def print_config(self) -> None: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    @retry_sftp
    def upload(self, local_path: str, remote_path: str) -> None: ...
    @retry_sftp
    def upload_from_memory(self, content: str | bytes, remote_path: str) -> None: ...
    @retry_sftp
    def download(self, remote_path: str | Path, local_path: str | Path | None = None, archive: bool = False) -> Path: ...
    def download_all(self, local_dir: str | Path | None = None, archive: bool = False) -> list[Path]: ...
    def list_files(self, remote_path: str = '.') -> list[RemoteFile]: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
