from ..models.utils import ParserConfig as ParserConfig
from _typeshed import Incomplete
from typing import Any, Callable

logger: Incomplete

class ParsersRegistry:
    config_path: Incomplete
    def __init__(self, config_path: str | None = None) -> None: ...
    def get_parser(self, type_name: str) -> Callable[..., Any]: ...
    def get_module(self, type_name: str) -> Any: ...
    def get_config(self, type_name: str) -> ParserConfig: ...
    def list_types(self) -> list[str]: ...
    def get_header_start(self) -> list[str]: ...
    def get_headers_and_types(self) -> dict[str, str]: ...

def get_registry() -> ParsersRegistry: ...
